# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'AKFacebook' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'FBSDKLoginKit'
pod 'FBSDKCoreKit'
pod 'FBSDKShareKit'
  # Pods for AKFacebook

end
